spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
planapi: 
 messages: 
  planSaveSucc: Plan Saved Succesfully
  plansavFail: Plan Save Failed
  planUpdateSucc: updated plan successfully
  planUpdatefail: updated plan failed
  planDeleteSucc: Delete plan Succesfully
  planDeleteFail: Delete Plan Failed
  PlanStatusChange: Plan Status Changed Sucessfully
  planStatusChangeFail: plan status change failed